version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.spring.nohttp:nohttp-checkstyle
    versions:
    - 0.0.5.RELEASE
    - 0.0.6.RELEASE
  - dependency-name: com.github.eirslett:frontend-maven-plugin
    versions:
    - 1.11.0
    - 1.11.2
